### ISSUE TITLE
Provide License

### ISSUE THREAD

**Issue by aharris88** [albinekb/open-pip-cli#9]
I couldn't find a license with this code. Could you add an open source license? I recommend MIT.

**Comment by albinekb** [comment]
Is this enough https://github.com/albinekb/open-pip-cli/blob/master/package.json#L12  ? @aharris88

**Comment by albinekb** [comment]
I'll add a licence file :) I saw your comment on another cli

**Comment by albinekb** [comment]
Done 👍

**Comment by aharris88** [comment]
Thanks! Sometimes I forgot to look in package.json.

**Comment by albinekb** [comment]
Yeah i guess it's better to have license right there too :)
